# Changes here will be overwritten by Copier
_commit: v0.0.5
_src_path: git@github.com:15r10nk/project-template.git
full_coverage: false
github_user: 15r10nk
insider_only: false
module_name: pysource_minimize
project_description: minimize python source code
project_main: true
project_name: pysource-minimize
python_versions:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'
show_project_logo: false
use_mkdocs: false
